### ISSUE TITLE
Sensors with RPM values display temperatures

### ISSUE THREAD

**Issue by JayXTQ** [5e/streamdeck-hwinfo-plugin#10]
For some reason, my RPM values are displaying temperatures, there is no overlaps with names or anything

**Comment by 5e** [comment]
Hi,

I’ve pushed an update (1.0.3) which might address this issue, you could manually download it from the repo in the Releases tab or wait till the Elgato store updates

**Comment by JayXTQ** [comment]
Oh yes, sorry, I downloaded it from the store thinking it was the same version. Thank you for the quick response!
