### ISSUE TITLE
The sensor buttons update very slowly after a while 

### ISSUE THREAD

**Issue by bredita** [5e/streamdeck-hwinfo-plugin#11]
It's been around 3 hours since I last quit stream deck and started it again. When I switch profiles its sometimes OK but other profiles update very slowly:

https://github.com/5e/streamdeck-hwinfo-plugin/assets/4368888/7b84f306-db1a-4323-b39e-048b1771e3a2

As you can see, after a few hours it updates very slowly. Quitting the stream deck software and starting it again fixes it, for a few hours.

If I stay one one profile it's fine, updates every second, but when I switch to another profile I haven't used in a while (or maybe at all since stream deck started) it updates very slowly.

It may be because I have _very_ many sensors mapped to buttons:
The main profile with 28 HWinfo sensors,
4 profiles with 31 sensors each
1 profile with 16 sensors

I switched back and forth between the profiles a few times, it didn't immediately help, but then I wrote this message, and now it's fast on all profiles. Maybe it had time to update the slow ones in the background and thats why they now update faster again?

https://github.com/5e/streamdeck-hwinfo-plugin/assets/4368888/b4cbb8e7-8aa0-43a5-a615-3d70977eddcf

**Comment by burstdragon323** [comment]
I am not experiencing this issue with my Stream Deck 15-key, try reducing the number of sensors you're using? I'm only using 6 of them.

**Comment by 5e** [comment]
Will attempt to investigate this in the upcoming days, I expect the solution to this will be refactoring how the plugin works resulting in less awaits and more direct communication between the PI and the backend sensor. 

Also I only have a mini stream deck so will need to debug it using the mobile Stream Deck app lol

**Comment by 5e** [comment]
I've done a refactor of how the plugin works (https://github.com/5e/streamdeck-hwinfo-plugin/tree/refactor-plugin) by reusing  data between buttons and just general code clean up.

@bredita If you're up for it, you can try out this refactor and let me know how it goes. For me I can instantly see an improvement as even after 15 minutes or so an 8x8 screen with 3 profiles would start slowing down.

The binary is in this folder https://github.com/5e/streamdeck-hwinfo-plugin/tree/refactor-plugin/Release

**Comment by bredita** [comment]
Installed. First impression: Seems a lot faster now. 

Will report back in a few hours and close the ticket if it is still OK.

Thanks for your extremely fast replies and fixes, again :)

**Comment by bredita** [comment]
Still no issues with the update speed, but I found another weird issue. Will make a separate issue for that one.

**Comment by bredita** [comment]
Still faster than ever
