### ISSUE TITLE
Incorrect values displayed after moving a button to an empty spot which previously contained a button

### ISSUE THREAD

**Issue by bredita** [5e/streamdeck-hwinfo-plugin#14]
(using the version from issue #11)

1. I move a button to some other place.
2. I move another button into the empty spot I just created.
3. All the values from the button I moved away in step 1 is now shown.
4. I select another sensor for the button which displays wrong values
5. The button now displays the correct info.
4. I switch back to the correct sensor value, and all is good.

https://github.com/5e/streamdeck-hwinfo-plugin/assets/4368888/43e698cf-e7c7-4ce5-858a-050cba8c849e

**Comment by 5e** [comment]
Thanks for all the help and testing, this should be a one liner to fix

**Comment by bredita** [comment]
Installed the new version today. Eeverything works now, as far as I can tell. Thanks again.
