### ISSUE TITLE
℃ display garbled code

### ISSUE THREAD

**Issue by SwordArtfeng** [5e/streamdeck-hwinfo-plugin#18]
![image](https://github.com/5e/streamdeck-hwinfo-plugin/assets/105966248/8db923f7-87b6-4360-a4eb-5cdd2854f751)
![image](https://github.com/5e/streamdeck-hwinfo-plugin/assets/105966248/231b9d55-805f-4db8-a47d-b0ff1b01b812)

**Comment by 5e** [comment]
Thanks, looks like a language thing as your computer uses a different Unicode character for the degree sign (I assume). 

Probably the better solution to this would be to allow user to specify a custom prefix/suffix than try to cater for all languages.

**Comment by SwordArtfeng** [comment]
Thank you very much for providing the plugin for our convenience. According to your instructions, how should I operate it? I also look forward to your update of the custom suffix function

**Comment by 5e** [comment]
I can't reproduce this on my machine. Maybe if you change the language of HWiNFO to English and restart it, it would work, but I am not confident.

Otherwise you will have to wait until a new update.

**Comment by SwordArtfeng** [comment]
Thank you very much, I have solved my problem.
Open the Control Panel, change the View mode to Category, select Change date, time or number format, click Manage, click Change system locale, and put a check mark in the box (Beta version: Use Unicode UTF-8 to provide global language support).
If you meet users like me, I hope you can help them.

**Comment by 5e** [comment]
https://github.com/5e/streamdeck-hwinfo-plugin/pull/19

Added custom suffixes
