### ISSUE TITLE
Configuration Warning for User

### ISSUE THREAD

**Issue by ChekTek** [5e/streamdeck-hwinfo-plugin#2]
The plugin requires enabling a sensor in the HWiNFO Gadget menu. It would be nice to show the user a warning message when the `Sensor` dropdown is empty, letting the user know they may need to configure something outside of the plugin. This could even link to the setup guide. 

![CleanShot 2024-01-30 at 17 44 41](https://github.com/5e/streamdeck-hwinfo-plugin/assets/6678919/30d677cd-f65f-43de-b54a-df8e761ec691)

**Comment by ChekTek** [comment]
Duplicate of #1

**Comment by 5e** [comment]
Thanks for the more in depth description than my own issue post 🤣, I'll keep this one open instead
