### ISSUE TITLE
Decimal values

### ISSUE THREAD

**Issue by Peat1111** [5e/streamdeck-hwinfo-plugin#20]
Am i missing something or is there a way to show decimal points? The gauges work with decimals but the value displayed is rounded, so i cannot see voltages for example. I'd like to see 3 decimal points.

**Comment by 5e** [comment]
You are right, by default it just truncates everything after the decimal point as I was silly and assumed why would you want to clutter such a small screen with decimal numbers. Totally forgot CPU voltages are a useful metric.

Should turn this into an optional setting.
