### ISSUE TITLE
How to change the download speed unit from kb/s to mb/s

### ISSUE THREAD

**Issue by SwordArtfeng** [5e/streamdeck-hwinfo-plugin#21]
If HWiNFO software cannot solve the problem, can you add this feature,
Because in practical use, monitoring is only meaningful when the download speed is high, and using kb is not so direct

**Comment by SwordArtfeng** [comment]
在HWiNFO里改了mb/s，但是实际显示的还是kb/s

**Comment by SwordArtfeng** [comment]
In HWiNFO, is 1MB equal to 1000kb or 1024kb

**Comment by 5e** [comment]
> In HWiNFO, is 1MB equal to 1000kb or 1024kb？

I'm not sure, try changing the multiply number until it looks correct
