### ISSUE TITLE
Cant read ram because too many digits...

### ISSUE THREAD

**Issue by Gittykittymitty** [5e/streamdeck-hwinfo-plugin#25]
When checking the used amount of Ram (psysichal memory used), it's almost impossible to read because of the overflow of digits that either causes some digits to be off screen, or you need to shrink it down so much its difficult to read. A solution to this problem would be to add the ability to cap the amount off digits showed on screen (like the one that you already included that limits decimals). Please add this, it would be greatly appreciated!

**Comment by 5e** [comment]
Hi, thanks for the report

I can see why you would want this added, but you can use HWiNFO to multiply/divide/change units as you wish, so seems redundant to add this into the plugin too as they would but do the same thing.

For example, to make a field more readable, you might want to change readings from MB to GB.

![image](https://github.com/5e/streamdeck-hwinfo-plugin/assets/107583272/47ab4d31-6dc9-4cab-8184-6f8e7e582cf2)

Right click on the sensor value

![image](https://github.com/5e/streamdeck-hwinfo-plugin/assets/107583272/b152eb00-7895-4d95-9ffa-157d64b83678)

To change from 24503MB to 24.50GB simply set the settings

![image](https://github.com/5e/streamdeck-hwinfo-plugin/assets/107583272/be5ac4a9-e8f8-473f-90ed-b5f9128ca1e4)

Then set the decimal places on the plugin settings 

![image](https://github.com/5e/streamdeck-hwinfo-plugin/assets/107583272/b461ef72-9ef4-4dd1-8892-b6e634d4481c)

**Comment by Gittykittymitty** [comment]
Thank you very much for the detailed answer on how to fix it! I appreciate it! I agree then that it would be kinda redundant to implement this into the plugin. Problems or confusion could maybe appear when you have two sources doing the same thing. Another solution to this would maybe just add a quick hint or instruction to the plugin that the number of digits and GB/MB can be changed within HWINFO. Just my opinion :)
Thanks!
