### ISSUE TITLE
node20.exe error when powering off machine

### ISSUE THREAD

**Issue by ktbsen** [5e/streamdeck-hwinfo-plugin#28]
Hi. Thanks for reading this and creating the hwinfo plugin. 

I am seeing a strange error. When powering off my machine i see a node20.exe error. "The application has stopped working". Likely due to the fact that stream deck or the plugin is not closing / stopping the node20.exe file properly, and thus it gets forced closed by windows when shutting down the machine. 

Troubleshooting steps done: 
removed node20.exe:
- error goes away, but also hwinfo-plugin does not work.

Image of error (not my image).
![node20.exe shutdown error](https://github.com/user-attachments/assets/f916bb99-26dc-453b-be5a-75391d69b7fd)

Image found in this reddit thread: 
https://www.reddit.com/r/elgato/comments/1eddk8d/node20exe_error/

**Comment by 5e** [comment]
I think this is a Node JS or StreamDeck issue, node20.exe is simply the Node JS process to run the StreamDeck software/plugins. Without node20.exe no Node JS plugins would work. There is nothing from my side I could do to fix this and for some reason this doesn't happen to me.
