### ISSUE TITLE
Set maximum value for displays

### ISSUE THREAD

**Issue by PureSpider** [5e/streamdeck-hwinfo-plugin#30]
Can the maximum value for the gauge and history diplays be set somewhere, either in hwinfo or in the plugin?
If not, can this be added?

**Comment by 5e** [comment]
![image](https://github.com/user-attachments/assets/2d189559-46e0-4fa0-9dc7-0f469501339b)

This? Or do you mean something else

**Comment by PureSpider** [comment]
That's exactly what I meant, turns out I'm just blind 🙈
Thank you!
