### ISSUE TITLE
frame drops in games

### ISSUE THREAD

**Issue by jimpard** [5e/streamdeck-hwinfo-plugin#33]
cheers 5e,

great plugin which does 50% of the job why i bought the stream deck. thank you so much :)

i just noticed a constant problem with your plugin that produces frame drops.

reproduced by deinstalling your plugin. 

in lower fps sections its more noticable. 

![Bild_2024-11-02_144155109](https://github.com/user-attachments/assets/16cfeaf1-2bde-4fee-b497-252ed7feb2d8)

would be awesome if you can have a look. 

greetings from germany
jimpard

**Comment by dotdean** [comment]
ah, even when i quit hwinfo it will do this

**Comment by 5e** [comment]
There’s many variables to control for this. This is a super light plugin which essentially all it does is read a value from registry once per second. It would be super unlikely this would cause any fps drops as it’s not a demanding task at all. 

It could be anything hardware/software related, or bad game optimisation. 

Feel free to reopen the issue if you gather more evidence.
