### ISSUE TITLE
adding sensors to gadget breaks the plugin

### ISSUE THREAD

**Issue by bredita** [5e/streamdeck-hwinfo-plugin#4]
I set it up, using just a few sensors in hwinfo gadget, displayed them on steam deck, all was fine.
Then added lots of sensors (including core clocks), causing the Index of the sensors in hwinfo gadget to change.
This broke the stream deck plugin - all my existing buttons now show core clock speeds.

This is probably because what used to be hwinfo gadget index 0-16 is now not the same sensor after I added (cpu core clock) sensors, the index of every sensor has now changed in HWInfo.

I suggest to rebuild the "list" of hwinfo index/description when a new sensor is added, and not assume that the index of a sensor never changes

**Comment by 5e** [comment]
Hi, thanks for the info

It does not go by the index, but rather by the sensor name, so deleting or adding new sensors shouldn’t affect it as it will retrieve the correct value everytime.

Maybe this is happening because you’ve removed a sensor value from HWiNFO but the SD plugin is still attempting to retrieve the sensor name in the registry and getting “frozen”, changing the plugin to show a valid sensor should unfreeze it. But I am just speculating and will investigate further.

the only issue I know which would happen is if you have 2 sensors with the exact same name and it may display the wrong value, but it shouldn’t break everything

**Comment by 5e** [comment]
Also, what version are you using? v1.0.0 had a bug which would something break the whole plugin and had been fixed in 1.0.1

**Comment by 5e** [comment]
Okay, I may have found your issue, for some reason HWiNFO saves the names wrong? Even though the items are called "Core 0 VID", in the registry they are saved as "Total CPU Usage" which will break my plugin as this is an issue I'm aware of and need to think of a way to fix (https://github.com/5e/streamdeck-hwinfo-plugin?tab=readme-ov-file#current-known-issues). 

As I am saving the info by the label name, this will just display the first value.

I will ask the HWiNFO developers if this is a bug or the intended way the Gadget storage is meant to work.

e.g. 

![image](https://github.com/5e/streamdeck-hwinfo-plugin/assets/107583272/f9b10d52-7fcf-46e3-bb17-d7451ffbb8cb)


![image](https://github.com/5e/streamdeck-hwinfo-plugin/assets/107583272/1b3e350f-a98a-46d6-b113-c7b95a099a02)

**Comment by bredita** [comment]
Yupp. While experimenting more in order to write a proper reply, I found that HWinfo must have a bug with renamed sensors.

What I did:
I set all sensors to "no" in HWINFO Gadget  and enabled just one. Your plugin works just fine.

Tried to rename a couple of sensors in hwinfo again (right click ->Customize in HWinfo):

For my Lexar drive:
Drive Temperature -> Lexar Drive Temp

For my samsung drive:
Drive Temperature -> Samsung Drive Temp

Then I exited HWInfo, and opened it again.
Now the "Lexar" and "Samsung" showed up under other drives.

So, I  figured I had done somwthing wrong, and changed them to the correct names I wanted, and the next time I started HWInfo it had messed them up again.

So this is a bug in HWinfo it seems. I'm using version 7.68-5300 of HWinfo BTW.

(Another thing I noticed - I had to set the thousands separator to nothing and the decimal separator to , (comma) in HWINFO to get the min/max values for fan speed to work. It wasn't happy with a fan speed of 1,234. Maybe because I am in norway and we use comma for decimal separator and period for thousands separator)

**Comment by 5e** [comment]
I found my issue https://github.com/5e/streamdeck-hwinfo-plugin/issues/4#issuecomment-1924582344 is only relevant if you have disabled monitoring like so, and then attempt to enable the HWiNFO Gadget monitoring on those sensors
![image](https://github.com/5e/streamdeck-hwinfo-plugin/assets/107583272/b18d3ccf-222d-4713-b5d1-53ed978368f9)

**Comment by 5e** [comment]
https://github.com/5e/streamdeck-hwinfo-plugin/issues/4#issuecomment-1924601198

I can't replicate this on my end, renaming a sensor in HWiNFO then restarting doesn't reset the name

![image](https://github.com/5e/streamdeck-hwinfo-plugin/assets/107583272/c75403b2-a753-4337-9bb2-4dff47899d55)

![image](https://github.com/5e/streamdeck-hwinfo-plugin/assets/107583272/a69dcce7-8e70-45de-a9ac-3040e851332e)

**Comment by bredita** [comment]
I still think there is till a bug in hwinfo.
I had some disabled sensors, have now enabled all sensors in HWinfo.

I then renamed my sensors like this:
![image](https://github.com/5e/streamdeck-hwinfo-plugin/assets/4368888/9f1f2bdc-e50a-473e-af92-39010bffdb9a)

Exited and restarted HWinfo and now it looks like this:
![image](https://github.com/5e/streamdeck-hwinfo-plugin/assets/4368888/7cf9c2f0-3972-4646-b0bc-ae31b65d1b21)

**Comment by 5e** [comment]
Yeah that doesn't look right, you could email the HWiNFO devs about it.

Also, the plugin gathers data from the HWiNFO Gadgets registry entries at `Computer\HKEY_CURRENT_USER\SOFTWARE\HWiNFO64\VSB` , maybe this HWiNFO bug is also somehow messing up the data in there, breaking my plugin

**Comment by bredita** [comment]
Figured out how to avoid that issue.
After renaming all the SMART temp sensors, I clicked the X in the bottom right, "Save and exit".
Waited a minute or so.
Then right clicked on systray icon, clicked quit.
Waited a few minutes before I restarted HWinfo.
Now the sensors with changed names are still in the right place.

So now I can set it all up, and I can have a page of too many sensors on my stream deck. Very nice.

Thank you for making this plugin and for your extremely fast replies, it's highly appreciated.

**Comment by bredita** [comment]
> Also, what version are you using? v1.0.0 had a bug which would sometimes break the whole plugin and had been fixed in 1.0.1

1.0.1

**Comment by bredita** [comment]
And that didn't last very long. 

I quit HWinfo, added my samsung USB NVME again, and the names were messed up again when I started HWinfo.
disconnecting the USB drive didn't fix it. 
Tried many things to work around the issue but in the end I decided to not do any drive monitoring for now.
Will install latest HWinfo and maybe contact them if the latest version has the same issue.
