### ISSUE TITLE
GPU sensors in the deck are reading as CPU sensors

### ISSUE THREAD

**Issue by burstdragon323** [5e/streamdeck-hwinfo-plugin#5]
Hi,

When using the plugin, the GPU sensors seem to read the CPU sensors.

I've attached a screenshot of this, and the deck and plugin are up to date.
![Screenshot 2024-02-02 122301](https://github.com/5e/streamdeck-hwinfo-plugin/assets/39740922/dcf52498-2978-4264-8755-98c08908f174)

**Comment by 5e** [comment]
Could you screenshot the list of sensors in the settings of the action? 
![image](https://github.com/5e/streamdeck-hwinfo-plugin/assets/107583272/25172e49-9fc9-401a-a15d-149016084d97)

**Comment by burstdragon323** [comment]
Ok.

In the top row, The first one is CPU Usage, and the second is supposed to be GPU Temperature.

The second row is Core Temperatures, and the second is GPU Memory Junction Temperatures.
![Screenshot 2024-02-02 123452](https://github.com/5e/streamdeck-hwinfo-plugin/assets/39740922/fe63dd7b-71ee-4f94-a82f-e11689aba360)
![Screenshot 2024-02-02 123638](https://github.com/5e/streamdeck-hwinfo-plugin/assets/39740922/e2b452d6-e6c1-4c13-8310-f83b57a67267)
![Screenshot 2024-02-02 123653](https://github.com/5e/streamdeck-hwinfo-plugin/assets/39740922/28e7bc3f-d87e-43e6-9fd1-8f631a0ad727)
![Screenshot 2024-02-02 123723](https://github.com/5e/streamdeck-hwinfo-plugin/assets/39740922/2a6b55f7-8f62-4f53-a18d-49f2b571791b)

**Comment by 5e** [comment]
Thanks, looks all fine

The plugin gathers data from the HWiNFO Gadgets registry entries at `Computer\HKEY_CURRENT_USER\SOFTWARE\HWiNFO64\VSB` (can be opened by typing regedit into windows search).

Like so:

![image](https://github.com/5e/streamdeck-hwinfo-plugin/assets/107583272/f0b19f44-b98b-4b29-8b9d-ce8f45f2c07a)


Could you see if the values there are all the same too? As all the plugin does is read the data from there, so I wonder if it is a HWiNFO problem saving wrong values?

**Comment by burstdragon323** [comment]
![image](https://github.com/5e/streamdeck-hwinfo-plugin/assets/39740922/3eb00702-a31e-476c-bfb2-303231ef8584)
 Here's what I have.

**Comment by 5e** [comment]
Also looks fine, thanks

Can you maybe try deleting the screens and just re-creating them? I am running out of ideas, it should all work fine with that setup

**Comment by burstdragon323** [comment]
No good regrettably.

**Comment by 5e** [comment]
I think I have found the issue, if you'd like to try the beta version, uninstall the plugin and let me know if this version now works

https://filebin.net/exctln3y5vechbtq/com.5e.hwinfo-reader.streamDeckPlugin

Else you can wait till this is pushed to the Elgato store in the next few days

**Comment by 5e** [comment]
Think I found the issue, it is relating to this issue too https://github.com/5e/streamdeck-hwinfo-plugin/issues/6

I have pushed a fix and compiled a beta version, if you would like to give it a go, uninstall the plugin and let me know if this version now works

https://filebin.net/exctln3y5vechbtq/com.5e.hwinfo-reader.streamDeckPlugin

Else this version will be pushed to the Elgato store in a few days

**Comment by burstdragon323** [comment]
Looks to be working, thanks for the fast update.
![image](https://github.com/5e/streamdeck-hwinfo-plugin/assets/39740922/24c15487-ac27-47ff-81a5-ca6b247b4d1b)
