### ISSUE TITLE
switch profile on button press (feature request)

### ISSUE THREAD

**Issue by bredita** [5e/streamdeck-hwinfo-plugin#9]
I have a button displaying cpu load.

I would like to be able to select a profile that will be opened when I press a button.

This would enable me to do things like:
- press the "CPU Load" button and have the stream deck switch to a page "Core details" showing _the individual CPU core_'s load.
- always be able to go to the main "Sensors" profile by pressing the top left button
- etc

Is this something you'd want and is it possible to do?

**Comment by 5e** [comment]
I'll look into it

**Comment by 5e** [comment]
Unfortunately the Stream Deck SDK does not allow me to change pages or change profiles

**Comment by bredita** [comment]
Thanks for checking.

Seems like its only possible to use switchToProfile to switch back to the _previously used profile_ (which could be useful, but is not exactly what I want), or to a _predefined profile in the manifest_ (which doesn't make much sense, since you have no idea what profiles I have defined on my streamdeck).
